[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/database/seeds/run-seeds.js ; node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3